### ISSUE TITLE
Tests, Tests, Tests !

### ISSUE THREAD

**Issue by oKcerG** [oKcerG/SortFilterProxyModel#11]
Write some tests,
Decide first with what test framework those should be written with, and then what to test and how.

**Comment by keithel** [comment]
I just created a PR #18 that adds test framework, and a set of tests for RangeFilter in the feature/filters-and-sorters branch. This PR uses the QtTest QML testing framework.

Minimal C++ is involved, just enough to compile in the module and a QtTest macro that expands to all that is needed for the main function.
