### ISSUE TITLE
filterPattern to hide 

### ISSUE THREAD

**Issue by saitej09** [oKcerG/SortFilterProxyModel#20]
Hi

I am trying to use filterPattern to hide from the list view. Default, it displays only what is filtered but now I would like it to hide the filtered and display the rest. Is there a get around for this?

Thanks!!

**Comment by oKcerG** [comment]
Hi,

There's 2 way you could achieve that :
* You could use negative look-ahead in your regex (`pattern: "(?!yourPattern)"`)
* or you could checkout the [feature/filters-and-sorters branch](https://github.com/oKcerG/SortFilterProxyModel/tree/feature/filters-and-sorters) of this repo and use a `RegexpFilter` with `inverted: true` :

```
import SortFilterProxyModel 0.2
//...

    SortFilterProxyModel {
        id: proxyModel
        sourceModel: yourSourceModel
        filters: RegexpFilter {
            roleName: "yourRoleName"
            pattern: "yourPattern"
            inverted: true
        }
    }
```

Cheers !

**Comment by saitej09** [comment]
Thanks!! 

I have used the second way and it works. I have one more issue. I have used a section delegate header component as described [here!](http://doc.qt.io/qt-5/qtquick-views-listview-sections-qml.html).  These are grouped based on the role I am using in the filter. When I use the model with the req filter, it removes the heading also which is essential for my work. I am finally trying to achieve some thing like [this](https://drive.google.com/file/d/0Bwll93gpLkGxa2FHd2w0aWdCcms/view). Any better implementation/ suggestions are appreciated.

**Comment by oKcerG** [comment]
I don't really get what you are trying to do.
Are you trying to hide specific sections with a `SortFilterProxyModel` ?
The `ListView` can only show sections it is aware of, so if no element corresponding to a section are present in a model, the `ListView` won't be able to show the section.

In your screenshot, the datas are quite heterogeneous, I don't think it makes sense to put all them in the same model.
The example code linked makes more sense, but I won't use a proxy model to hide sections here if that's what you want to do. I would just set a flag for each section to hide the elements corresponding to this section but keep the section delegate visible.

**Comment by saitej09** [comment]
Ya I jus wanted to give this a shot if it can be done via SortFilterProxyModel. I will do with the usual flags. Thanks.
