### ISSUE TITLE
Typo in SortFilterProxyModel/filter.cpp

### ISSUE THREAD

**Issue by adenever** [oKcerG/SortFilterProxyModel#21]
at Line  441   qmlRegisterType<RegexpFilter>("SortFilterProxyModel", 0, 2, "RegexpFilter");
according to documentation/sample complex filtering & camel case tradition at there the "E" is uppercase in "ExpFilter" like

    qmlRegisterType<RegexpFilter>("SortFilterProxyModel", 0, 2, "RegExpFilter");

Class name could be also in camel case

**Comment by oKcerG** [comment]
Thank you for pointing out this mistake
