### ISSUE TITLE
Access to QSortFilterProxyModel::mapToSource

### ISSUE THREAD

**Issue by timangus** [oKcerG/SortFilterProxyModel#23]
Occasionally it would be useful to be able to access QSortFilterProxyModel::mapToSource from within a QML context. It is already Q_INVOKABLE, but since it takes a QModelIndex as its parameter and also returns a QModelIndex, it is quite awkward to use. In order to make sense of the return value we need to hop back into C++ to get the value of QModelIndex::row(), which is much more useful on the QML side, than the raw QModelIndex.

Perhaps SortFilterProxyModel could provide a more QML friendly interface to mapToSource? (and also sourceToMap.)

**Comment by oKcerG** [comment]
This is indeed definitely needed. Thanks for the suggestion.

**Comment by iberiozko** [comment]
This is absolutly obvious to implement. Just add a function:

Q_INVOKABLE int mapRowToSource(int i) {
        QModelIndex sourceIndex = mapToSource(index(i, 0));
        return sourceIndex.row();
}

Thanx for a nice project ))

**Comment by oKcerG** [comment]
Indeed it isn't hard, the hard part is writing tests.
From now one I plan to write tests for features I add, and the ones already present, it will hopefully prevent stupid errors in trivial code like #22 and others not so trivial.

**Comment by iberiozko** [comment]
Reverse resolving:

```cpp
Q_INVOKABLE int mapRowFromSource(int i) {
      QModelIndex myIndex = mapFromSource(sourceModel()->index(i, 0));
      return myIndex.row();
}

```

**Comment by iberiozko** [comment]
This really should be coded in .h header file, for the optimizer to decide making this inline.

**Comment by timangus** [comment]
Thanks!
