### ISSUE TITLE
Add a get method

### ISSUE THREAD

**Issue by oKcerG** [oKcerG/SortFilterProxyModel#24]
The possibility of accessing an element imperatively can be useful.

The function interface coud look like this : get(rowNumber, roleName = "") returning all the roles or just the specified role for this element.
An alternative taking a QModelIndex could also be made.

**Comment by iberiozko** [comment]
This should be not so obvious as expected, because sourceModel property is of type QAbstractItemModel and does not implement get() method directly.

A good workaround is to use QML proxy component like this: ListProxyModel.qml:

```qml
import QQSFPM 0.2
SortFilterProxyModel {
        function get(i) { return sourceModel.get(mapRowToSource(i)) }
        function set(i, v) { return sourceModel.set(mapRowToSource(i), v) }
        function getProperty(i, p) { return sourceModel.get(mapRowToSource(i))[p] }
        function setProperty(i, p, v) { return sourceModel.setProperty(mapRowToSource(i), p, v) }
        function append(v) { return sourceModel.append(v) }
        function remove(i) { return sourceModel.remove(mapRowToSource(i), 1) } // Removing with count > 1 should be a bit tricky
        // ... Etc other proxying functions to QML ListModel component.
}
```

**Comment by oKcerG** [comment]
No but it does implement [`data`](http://doc.qt.io/qt-5/qabstractitemmodel.html#data). One could use that to implement the `get` function in SFPM

**Comment by iberiozko** [comment]
Yes, but after that one should wish to implement set(), append(), remove() and otner ListModel-specific methods. And after that - all methods/properties for all components inheriting QAbstractItemModel.

But in fact, programmer really is informed on what kind sourceModel is, and is able to implement desiered QML proxy methods, using mapRowToSource/mapRowFromSource.

**Comment by oKcerG** [comment]
I don't think I will implement modification functions after, I only want to offer some convenience functions to read data.
I believe you shouldn't modify the source model via the proxy model, but instead modify directly the source model by its own api, and not with its QAbstractItemModel's functions.

Providing data to views is the main goal of this class but sometimes accessing data imperatively is needed and I want to provide this functionality easily.

**Comment by iberiozko** [comment]
Providing data via proxyModel's methods is a bad idea.

You cannot realy imagine what kind of model is your sourceModel(). Look into sources - QSortFilterProxyModel really implements just sorting and filtering, and nothing else.

Exactly: it provides data() with applied sorting/filtering, btw. avoiding useless calling to filterAcceptsRow().
Nothing more.

Your SortFilterProxyModel is a great way to deal with sort and filter.

Okkk, next message follows.

**Comment by oKcerG** [comment]
This feature won't need need to know anything about the underlying source model, it will only returns a QVariant (or a QVariantMap for multiple roles), something that every `QAbstractItemModel` returns.
It also won't create more calls to `filterAcceptsRow()`.

**Comment by iberiozko** [comment]
Why are so sure that get() method is used?

I use my own getO (uint128_t oid) to acces my model.

**Comment by iberiozko** [comment]
Thus, i have:

void getO(oid) { ... }
void getPropertyO(oid, p) { return getO(oid)[p]; }
/// etc

**Comment by iberiozko** [comment]
Fuck!

You say you do not wish to know anything about underlying data.

But implementing get() you MUST know about the data!

**Comment by iberiozko** [comment]
get()  is defined in each class individually!

**Comment by oKcerG** [comment]
This get function will be used to access data from the proxymodel using integer indexes.

I don't know what you are talking about your `getO`, but the plan here is to add a friendlier API than `data` :

`get(i, "roleName")` will just return `data(index(i, 0), roleIndexFromRoleName("roleName"))`, no need to know about the source model here.

**Comment by iberiozko** [comment]
Ok.

Just test your model with TableView.

**Comment by iberiozko** [comment]
The get() function is used incorrectly in this case.

What do you say about set() and and the whitch one of set we are talking here?

this.set(i, this.get(i)) should be immutable.

**Comment by oKcerG** [comment]
Hello @iberiozko , do you see any problems with the implementation of this feature brought by cb26d89 ?

**Comment by iberiozko** [comment]
Hello.

You see, the fact is that sourceModel can be of any class inheriting QAbstractItemModel. Get() method is not specified by QAbstractItemModel.

For example, the get() is defined in QQmlListModel class, the one that is background for QML ListModel type. But, our sourceModel may be of class QFileSystemModel, that does not implement get() at all. Accessing data() for it like you do may return something very unpredictable

So, if one wishes to have convinient proxying models providing same methods as ListModel, the best way should be to have QML proxy type implementing required method, let's call it ListProxyModel:

```
// ListProxyModel.qml
SortFilterProxyModel {
  function get(i) { return sourceModel.get(mapRowToSource(i)) }
  function set(i, v) { return sourceModel.set(mapRowToSource(i), v) }
  function getProperty(i, p) { return sourceModel.get(mapRowToSource(i))[p] }
  function setProperty(i, p, v) { return sourceModel.setProperty(mapRowToSource(i), p, v) }
  function append(v) { return sourceModel.append(v) }
  function remove(i) { return sourceModel.remove(mapRowToSource(i), 1) }
}
```

And after that use it like:

```
ListProxyModel {
  id: someProxiedListModel
  sourceModel: someBigListModel
  filters: [ /* filters etc */ ]
}

onSomeExampleEvent: {
  someProxiedListModel.append({ firstName: 'john', lastName: 'smith' })
  console.log(someProxiedListModel.get(someProxiedListModel.count() - 1))
  // Etc with other methods
}
```

**Comment by oKcerG** [comment]
The mapping functions will be pushed soon but those aren't relevant to this issue. `QSortFilterProxyModel` handles the mapping for us when calling `data`.
I don't see how your `ListProxyModel` is superior to the `get` methods I've implemented. In fact, I believe they are inferior.

I don't need the source model to have a `get()` method implemented, I only need it to have a `data()` method, and all models have it.

> Accessing data() for it like you do may return something very unpredictable

Are you referring to the fact that I call `data()` with the column set as 0 and no parent index ? That's true, but also intentional. Those `get` functions are only meant as a convenience functions for single-column multi-roles models, the majority of the models I've encountered in QML.
I agree that should be clearer, and the lack of documentation doesn't really help. I should really work on that.
For others model you can still call `data()` where you can pass an index and a role number thanks to the `roleForName()` method this commit added. One use-case I haven't treated is if you want to get all roles for a specific index. I might consider adding it if an issue is created for it.

I don't plan to add set, add or remove methods cause I believe that a lot of models aren't really editable like that and that you should call their specific API to modify them instead. For that the `mapToSource` and `mapFromSource` are needed.

**Comment by iberiozko** [comment]
Yes, most popular models return exactly data(index(row, 0)) for get(), but no one can say they MUST do it. You see, the problem is that a model's get() method MAY really return something different than data(index(row, 0)).

data() is used for views etc, but get() is used as API call exactly the same way as set(), append() etc.

BTW, I'm not sure if defining get() directly as JS function of QML type will override default get() in model. If so, let your get() will be default convinience helper, and one is able to redefine in in QML/JS as he wishes.

**Comment by oKcerG** [comment]
> Yes, most popular models return exactly data(index(row, 0)) for get(), but no one can say they MUST do it.
Most models don't have a get(). My get() function is by definition a convenience function to access data for a given row and the first column of a model.
If you want to call a specific api of a source model, you should call it directly and not via the proxy. It needs #23 to be realized though.

**Comment by iberiozko** [comment]
Ok, let us leave this as is :)

Anyway, one can implement myGet() method and use it as he wishes.
