### ISSUE TITLE
FeatureRequest: Function filter type

### ISSUE THREAD

**Issue by iberiozko** [oKcerG/SortFilterProxyModel#27]
That should be real;y a nice feature for tricky models. See example in code:

```qml
SortFilterProxyModel {
    // ...
    filters: [
        Function {
            property real minSomething
            property real maxSomething
            acceptsRow: function(row) {
                if (row.somerole.something > minSomething && row.somerole.something < maxSomething) { return true }
                else if (Math.random() < 0.1) { return true }
                else { return false }
            }
        }
    ]
}
```

**Comment by oKcerG** [comment]
This functionality is already here with `ExpressionFilter`

Your example could be written like this :

```qml
SortFilterProxyModel {
    // ...
    filters: [
        ExpressionFilter {
            property real minSomething
            property real maxSomething
            expression: {
                if (model.somerole.something > minSomething && model.somerole.something < maxSomething) { return true }
                else if (Math.random() < 0.1) { return true }
                else { return false }
            }
        }
    ]
}
```

Alternatively you could write it with multiple filter like so :

```qml
SortFilterProxyModel {
    // ...
    filters: AnyOf {
        RangeFilter {
            roleName: "someRole"
            minimumValue: foo
            maximumValue: bar
        }
        ExpressionFilter {
            expression: Math.random() < 0.1
        }
    }
}
```

Sorry about the lack of the documentation.

**Comment by iberiozko** [comment]
No-no-no!

My somerole is an QVariant type (a JS object), it has a property somerole.something on the value of i am making a decision.

**Comment by iberiozko** [comment]
Perhaps, should look like

```qml
ExpressionFilter {
    expression: function(...) { ... }
}
```

**Comment by iberiozko** [comment]
Ok, let me test this, please. Possibly my request is already implemented.

**Comment by oKcerG** [comment]
If you need help or to have a more direct chat, I'm available on IRC, #qt-quick in Freenode, my nickname there is GrecKo.

**Comment by iberiozko** [comment]
/me at skype: iberiozko
Sorry, I do not use IRC.
FYI: I really am trying to use qqsfpm in my production. I've looked into the code and am feeling it looks good enough. No major bugs should exist.
All my tests and suggestions are based on real production.

**Comment by oKcerG** [comment]
And sorry I don't use Skype ;)

I also use SortFilterProxyModel in production but I believe some tests are needed to guarantee a basic level of quality assurance.

**Comment by iberiozko** [comment]
Shit.
Meet me on IRC lately.

**Comment by iberiozko** [comment]
Let us be calm, pkease, hekp  me iconnecting to IRC.

**Comment by iberiozko** [comment]
да блять, я нихуя не понимаю и ни разу этим гмковским irc не пользовался.

**Comment by oKcerG** [comment]
Here is a link to the webchat if you don't have an IRC client : http://webchat.freenode.net/?channels=%23qt-quick

**Comment by iberiozko** [comment]
Lots of weird text, I cannot deal with that stuff.

**Comment by iberiozko** [comment]
Weird issue, should be closed.
