### ISSUE TITLE
Examples: how to implement cascading models similar to primary/foreign keys relations inSQL

### ISSUE THREAD

**Issue by iberiozko** [oKcerG/SortFilterProxyModel#30]
I have already implemented that, need to cleanup my code and contribute it for you.

**Comment by oKcerG** [comment]
Did you mean something that could be used to do this ?
![Cascading List](https://cloud.githubusercontent.com/assets/349268/23213689/28000d3c-f90c-11e6-8ed8-0becef557d6d.png) 
(The multiple columns part for the font)

**Comment by iberiozko** [comment]
Yes, something like this is possible also.

But in my case I have several database tables, reflected by QT models. These tables have foreign keys relations, so I wish them to be editable the way like ASP.NET datasets do this.

**Comment by iberiozko** [comment]
Ae. I've finally understood your example about fonts.,Ok, will try to use it for my example code.

Will be lately )
