### ISSUE TITLE
ValueInList, ObjectProperty filters

### ISSUE THREAD

**Issue by iberiozko** [oKcerG/SortFilterProxyModel#35]
Are implemented, running in my production, but I do not know how to contribute it.

```
ValueInListFilter {
  roleName: 'someN'
  value: [ 'some1', 'some2', 'just5' ]
}
```

**Comment by iberiozko** [comment]
ValueInListFilter {
  roleName: 'someR_key'
  value: Obj.keys(someObj.dataholder)
}

**Comment by mardy** [comment]
I also would like to have this, as well as an IndexInListFilter. In the meantime, one can use the ExpressionFilter:

```
    UploaderModel {
        id: uploaderModel
    }

    SortFilterProxyModel {
        id: selectedUploaders
        property var selectedIndexes: [1, 3]
        sourceModel: uploaderModel
        filters: [
            ExpressionFilter {
                expression: selectedUploaders.selectedIndexes.indexOf(model.index) >= 0
            }
        ]
    }
```

@iberiozko Where is your code? If you don't know how to contribute it, I could do it for you. Though, contributing is rather easy: you fork the project, get a local copy of your fork, make your changes, push, and then in the web interface you'll see a link to create a merge request.

**Comment by oKcerG** [comment]
> I also would like to have this, as well as an IndexInListFilter

Maybe adding a generic `ListFiter` (with a  better name) instead of a  *InListFilter for every existing filters make sense. With a possible API like this :

```
ListFilter {
    property: "value"
    list: [ 'some1', 'some2', 'just5' ]
    ValueFilter {
        roleName: 'someN'
    }
}
```
Specifying `property: "value"` could be maybe omitted by using `Q_CLASSINFO("DefaultProperty",..)`.

Alternatively, each filter could handle being passed a list like `PropertyAnimation` does (it has `property` for animating a single prop and `properties` for multiple props)
Possible API :

```
ValueFilter {
    roleName: 'someN'
    values: [ 'some1', 'some2', 'just5' ]
}
```

The drawback of this solution is that this complexifies each filter.

**Comment by iberiozko** [comment]
Guys...

Sorry, /me having no time right now neither for contributing, nor for cleaning the code. The patch is implemented as a package diff for buildroot.org package.

Please contact me on iberiozko@mail.ru, or skype: iberiozko - I will offer you the diff. You than may use it than as ypu wish.

**Comment by iberiozko** [comment]
[0001-rework-by-iberiozko.zip](https://github.com/oKcerG/SortFilterProxyModel/files/1181328/0001-rework-by-iberiozko.zip)

Just take it as zipped diff, one knowing patch should easelly apply it.
