### ISSUE TITLE
module "SortFilterProxyModel" is not installed

### ISSUE THREAD

**Issue by karahman1993** [oKcerG/SortFilterProxyModel#36]
I already download the deposit, and i added include(SortFilterProxyModel/SortFilterProxyModel.pri) in my .pro, but When I put "import SortFilterProxyModel 0.2"

i have this error:  qrc:/main.qml:04 module "SortFilterProxyModel" is not installed

so please i need help

**Comment by kubark42** [comment]
This error indicates that you haven't registered the QML type with the engine. In your c++ file (`main.cpp`?), you will need to add the following line:

`qmlRegisterType<QQmlSortFilterProxyModel>("SortFilterProxyModel", 0, 2, "SortFilterProxyModel");`

to somewhere before you load your main QML file. Typically you should be able to add it all the way at the top, just after the `int main(int argc, char *argv[])`.

Makes sense?

P.S. The `README.md` leaves out this step, but it's common across all QML plugins. If you find a good link which describes this generically, maybe report it here and the project maintainers can integrate it into the `README.md`?

**Comment by oKcerG** [comment]
Just including the SortFilterProxyModel.pri should be enough. The registering of the type should be taken care of automatically by https://github.com/oKcerG/SortFilterProxyModel/blob/c723de3fb5efa42e426bba8b835f742e1fa97d15/qqmlsortfilterproxymodel.cpp#L369-L373

@karahman1993 Can you provide an minimal reproducible example of your problem ? Preferably in a [Gist](gist.gisthub.com) with 3 files ( a .pro, main.cpp and main.qml)

**Comment by kubark42** [comment]
@oKcerG, how right you are. I think this might be related to https://github.com/oKcerG/SortFilterProxyModel/issues/40. I figured out the registration back before I realized that `qpm` didn't yield latest results. I just pulled out the `qmlRegisterType` line and this time, with SortFilterProxyModel 0.2.0 from git, everything worked on its own. Cool stuff!
