### ISSUE TITLE
SortFilterProxyModel with PyQt

### ISSUE THREAD

**Issue by karahman1993** [oKcerG/SortFilterProxyModel#37]
How do I use this SortFilterProxyModel which is in c ++ with PyQt??

**Comment by iberiozko** [comment]
You can use my patch from https://github.com/oKcerG/SortFilterProxyModel/issues/25 to build as standalone plugin.

After building you get a libqmlqsortfilterproxymodelplugin.so library. You should put it (and qmldir file) into /usr/qml/QQSFPM/ or whereever your QML plugins live. Then you can do "import QQSFPM 0.2" as usual.

qmldir file:
```
module QQSFPM
plugin qmlqsortfilterproxymodelplugin
```

**Comment by karahman1993** [comment]
i tried your example, I had this error "could not find the executable, please specify one"
Please i am beginner, Can you Explain more ??

**Comment by iberiozko** [comment]
Hmm, let's try.

1. Checkout code.
2. Create plugin.cpp and SortFilterProxyModel.pro as in #25.
3. qmake
4. make
5. You get libqmlqsortfilterproxymodelplugin.so
6. Put it into /usr/qml/QQSFPM/
7. Put qmldir file nearby.
8. Profit.

Feel free to contact me on skype: iberiozko.

**Comment by karahman1993** [comment]
I tried but it did not work!!!! so i show you my file "finale":

-----------------------------------

-finale
     finale.pro
    -SortFilterProxyModel
          SortFilterProxyModel.pro
         -Header
                filter.h
                qmlqsortfilterproxymodel.h
                sorter.h
         -Source
                filter.cpp
                plugin.cpp
                qmlqsortfilterproxymodel.cpp
                sorter.cpp
  -Sources
         main.py
  -Ressources
        -qml.qrc
               -/
                     main.qml

------------------------------------------------------
when i try this, i get : "qmlqsortfilterproxymodelplugin.dll" not "libqmlqsortfilterproxymodelplugin.so" so when i put this .dll and qmldir in my folder (stage/finale) and i run my PyQt i get error "module QQSFPM is not installed). so is the bug in the architecture that I showed you ?? or another problem??
thank you

**Comment by oKcerG** [comment]
Duplicate of #25
