### ISSUE TITLE
Inverse filtering (where value is not equal to)

### ISSUE THREAD

**Issue by 0xFEEDC0DE64** [oKcerG/SortFilterProxyModel#38]
I need filtering for `SortFilterProxyModel.FixedString` but with a "does not equal to" functionality.

I dont think this feature exists yet and I would like to suggest it as a feature request. I am not familiar enough with the library to implement it on my own.

I dont want to use regexes with negative look aheads as I would have to escape the search string beforehand.

**Comment by 0xFEEDC0DE64** [comment]
Has been solved.

I just learned about the filters property and added a filter with `inverted: false` property.

**Comment by oKcerG** [comment]
Instead of using `RegExpFilter` with `SortFilterProxyModel.FixedString`, you could also use `ValueFilter`. You would still have to use the `inverted` property though.
