### ISSUE TITLE
Compilation issue at SwitchRole

### ISSUE THREAD

**Issue by dnvdmitry** [oKcerG/SortFilterProxyModel#54]
class SwitchRole : public SingleRole, public FilterContainer
{
    Q_OBJECT
    Q_INTERFACES(qqsfpm::FilterContainer)
    Q_PROPERTY(QString defaultRoleName READ defaultRoleName WRITE setDefaultRoleName NOTIFY defaultRoleNameChanged)
    Q_PROPERTY(QVariant defaultValue READ defaultValue WRITE setDefaultValue NOTIFY defaultValueChanged)
    Q_PROPERTY(QQmlListProperty<qqsfpm::Filter> filters READ filtersListProperty)

public:
    _**using ProxyRole::ProxyRole;**_

ProxyRole is not a direct base for SwitchRole, so inherit constructors are prohibited

**Comment by oKcerG** [comment]
Thanks for reporting this issue.

Indeed this look like I forgot to commit stuff after refactoring ProxyRole.
I will do it when I get back from work.
