### ISSUE TITLE
Crash on windows

### ISSUE THREAD

**Issue by ducmaxime** [oKcerG/SortFilterProxyModel#6]
Hello, thank you for this great lib. But i have a crash on windows. Qmlregistertype error. Any Idea ? Thx 

![pasted image at 2016_08_22 01_17 pm](https://cloud.githubusercontent.com/assets/6499846/17853119/0b805fb8-686b-11e6-9a50-d09a2065bf1d.png)
![pasted image at 2016_08_22 01_18 pm](https://cloud.githubusercontent.com/assets/6499846/17853120/0babfe70-686b-11e6-8050-0d87dc000a0e.png)

**Comment by oKcerG** [comment]
Yeah,
This should be related to https://github.com/benlau/quickflux/issues/7
I forgot to fix that issue,  I'll do it ASAP.

Thanks for reporting it

**Comment by ducmaxime** [comment]
Thanks a lot !!

On 22 Aug 2016, at 15:01, oKcerG <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah,
This should be related to benlau/quickflux#7<https://github.com/benlau/quickflux/issues/7>
I forgot to fix that issue, I'll do it ASAP.

Thanks for reporting it

**Comment by oKcerG** [comment]
Fixed by 45d16933c39ac30fdf88955649919647d036df6e

**Comment by Nooay** [comment]
Hi,
i have the same crash with MSVC2015 32 bits:

![qmlregistertype](https://user-images.githubusercontent.com/31699119/30900828-aa4dce7e-a365-11e7-9d55-4281957bab82.jpg).

An idea ?

(Btw sorry for that late feedback about 'finished filtering event', i'm coming back to you as soon as i can work on it)

In advance, thanks for your support.

**Comment by oKcerG** [comment]
@Nooay do you have a complete stacktrace ?

**Comment by Nooay** [comment]
Here are the complete crash informations

![crash](https://user-images.githubusercontent.com/31699119/30919784-b52fca94-a3a2-11e7-94a2-87bc3bcb3f0a.jpg)
