### ISSUE TITLE
Member access into incomplete type - build error

### ISSUE THREAD

**Issue by husninazer** [oKcerG/SortFilterProxyModel#68]
I just added the .pri location to my pro file and when compiling the following error.

error: member access into incomplete type 'const qqsfpm::QQmlSortFilterProxyModel' 
return proxyModel.sourceData(sourceIndex, m_roleName);

                  roleFilter.cpp Line 41

**Comment by oKcerG** [comment]
Hello, it works here.

Are you sure there is no change in your source code?
What's weird is that `QQmlSortFilterProxyModel` is not in the `qqsfpm` namespace in the code. Your error message seems to imply it is.

**Comment by husninazer** [comment]
Hi, this was a setup issue from my side as the class name was already there in the project defined earlier.
