### ISSUE TITLE
[Question] Order of bindings in QML matters regarding sorting

### ISSUE THREAD

**Issue by Ryochan7** [oKcerG/SortFilterProxyModel#7]
To test out SortFilterProxyModel, I made a very simple stopwatch application that utilizes a QAbstractListModel for the base model to store time elapsed and differences in times between laps. A SortFilterProxyModel is then used to sort the data in descending order of elapsed time so the newer entries appear first in my ListView.

Anyway, while initially trying to use the proxy model in the main QML file, it did not appear to work. Debugging the underlying class showed that sortOrder was being set before sortRoleName despite the order being flipped in the QML declaration. This caused sorting to not work as intended. Setting sortOrder in QML first before setting the sortRoleName was necessary in order for the instance of SortFilterProxyModel to do its job and sort the data the way I wanted. Here is how I am using the SortFilterProxyModel in QML.

```
SortFilterProxyModel {
    id: filteredLapModel
    sourceModel: testModel
    sortOrder: Qt.DescendingOrder
    sortRoleName: "lapTime"
}
```

Is this expected behavior? I would normally want to set the sortRoleName before the sortOrder. Is there any way to change the behavior so sortRoleName can be declared first in the QML declaration and work?

**Comment by oKcerG** [comment]
Thanks for the report, it is indeed a bug.
The evaluation order of QML bindings is undefined and we shouldn't rely on it.

If you want to test out SortFilterProxyModel, check the new branch : https://github.com/oKcerG/SortFilterProxyModel/tree/feature/filters-and-sorters
I haven't written the documentation yet (I'm in the process of doing it), but it enables a lot of new cool things with the `filters` and `sorters` list properties, check `filter.h` and `sorter.h` to see what you can put in those list properties.

For example, you can sort on multiple roles with `sorters: [RoleSorter { roleName: "lapTime" }, RoleSorter { roleName: "lastName" } ]`.
Or filters if a lapTime is under a certain time, or is the first time recorded : filters: AnyOf { RangeFilter { roleName: "lapTime"; maximumValue: timeSlider.value } IndexFilter { maximumIndex: 0 } }`

**Comment by Ryochan7** [comment]
Thank you for the fix. The features that you are implementing in the filters-and-sorters branch look like they will be very useful.
