### ISSUE TITLE
Compile error: Forward declaration of class cannot have a nested name specifier

### ISSUE THREAD

**Issue by encombhat** [oKcerG/SortFilterProxyModel#70]
Environment:
- Qt 5.13.2
- CMake 3.15.5
- AppleClang 11.0.0
- macOS 10.15.2

When embedding SortFilterProxyModel, the compilation failed with "Forward declaration of class cannot have a nested name specifier, expand from the macro class QT_PREPEND_NAMESPACE(QQmlExpression);".

Apparently this only happened on latest master and did not happen before.

**Comment by ggalt** [comment]
Same issue.  My environment is:
Qt 5.13.2 
qmake 3.1
MinGW 7.3.0 (64-bit)
Windows 10 (1809)

**Comment by ggalt** [comment]
FYI, I just confirmed that reverting to 36befdd works.

**Comment by oKcerG** [comment]
Sorry about that, I should have looked into this earlier and not push broken code.
